# Generated by Django 2.2.2 on 2019-06-20 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealTracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='name',
            field=models.CharField(default='Madras Chettinaad', max_length=100),
        ),
        migrations.AddField(
            model_name='meal',
            name='notes',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='meal',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
